SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `TRAVEL_PRODUCT_INFO`;
DROP TABLE IF EXISTS `TRAVEL_PRODUCT_PRICE`;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE `TRAVEL_PRODUCT_INFO`(
    `PROD_UNI_CODE` VARCHAR(32) NOT NULL,
    `OTA_ID` INT(4) NOT NULL,
    `PROD_TYPE` VARCHAR(16) NOT NULL,
    `OTA_PROD_ID` VARCHAR(16) NOT NULL,
    `PROD_NAME` VARCHAR(255),
    `TA_NAME` VARCHAR(255),
    `PACKAGE_NAME` VARCHAR(255) NOT NULL,
    `TRAVEL_PLAN` VARCHAR(255),
    `TOUR_PARTY` INT(4),
    `PARYT_PALCE` VARCHAR(20),
    `TOUR_DESTN` VARCHAR(255),
    `TOUR_DAYS` VARCHAR(20),
    `TOUR_PATH` VARCHAR(255),
    `PROD_LINK` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`PROD_UNI_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TRAVEL_PRODUCT_PRICE`(
    `PROD_UNI_CODE` VARCHAR(32) NOT NULL,
    `DATE` DATE NOT NULL,
    `CITY` VARCHAR(20) NOT NULL,
    `PRICE` DECIMAL(6,2) NOT NULL,
    FOREIGN KEY(`PROD_UNI_CODE`) REFERENCES TRAVEL_PRODUCT_INFO(`PROD_UNI_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;